# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/longxin/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_mul/unsigned_mul.xci
# IP: The module: 'unsigned_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/longxin/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_mul/unsigned_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_mul'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /data/longxin/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_mul/unsigned_mul.xci
# IP: The module: 'unsigned_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/longxin/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_mul/unsigned_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_mul'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
