# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/soc_up.xdc

# IP: ip/icache_data_ram/icache_data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==icache_data_ram || ORIG_REF_NAME==icache_data_ram} -quiet] -quiet
