# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/TOP/config.h
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/utility.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_defines.h
}
set_property file_type "Verilog Header" [get_files /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/TOP/config.h]
set_property file_type "Verilog Header" [get_files /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/utility.v]
set_property file_type "Verilog Header" [get_files /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_defines.h]
read_verilog -library xil_defaultlib {
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/apb_dev_top.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/apb_mux2.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/AMBA/axi2apb.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/AMBA/axi_mux.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/bd.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/CONFREG/confreg.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/csr.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/DMA/dma.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/dma.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/ethernet_top.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/SPI/godson_sbridge_spi.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/mac.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/mac2axi.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/mac_axi.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/mac_top.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/maccsr2axi.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/macdata2axi.v
  /data/longxin/learning/ic_design/chisel-template/mycpu_top.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/NAND/nand.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/nand_module.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/raminfr.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/rc.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/rfifo.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/rlsm.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/rstc.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/tc.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/tfifo.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/MAC/tlsm.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_receiver.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_regs.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_rfifo.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_sync_flops.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_tfifo.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_top.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/APB_DEV/URT/uart_transmitter.v
  /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/rtl/TOP/soc_up_top.v
}
read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/icache_data_ram/icache_data_ram.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/icache_data_ram/icache_data_ram_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_board.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_late.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0.xci
set_property used_in_synthesis false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_clocks.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32.xdc]
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/signed_mul/signed_mul.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/signed_mul/signed_mul_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_mul/unsigned_mul.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_mul/unsigned_mul_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/btb_data_ram/btb_data_ram.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/btb_data_ram/btb_data_ram_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/btb_tag_ram/btb_tag_ram.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/btb_tag_ram/btb_tag_ram_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/dcache_data_ram/dcache_data_ram.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/dcache_data_ram/dcache_data_ram_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/signed_div/signed_div.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/signed_div/signed_div_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_div/unsigned_div.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/unsigned_div/unsigned_div_ooc.xdc]

read_ip -quiet /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pht_data_ram/pht_data_ram.xci
set_property used_in_implementation false [get_files -all /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pht_data_ram/pht_data_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/soc_up.xdc
set_property used_in_implementation false [get_files /data/longxin/BIT_1_huangxingze/display/soc_up_for_system/vivado_xpr/soc_up.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_up_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_up_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_up_top_utilization_synth.rpt -pb soc_up_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
