# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ddddddd/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/sram_128x32/sram_128x32.xci
# IP: The module: 'sram_128x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ddddddd/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/sram_128x32/sram_128x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_128x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ddddddd/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/sram_128x32/sram_128x32.xci
# IP: The module: 'sram_128x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ddddddd/learning/ic_design/nscscc-group/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/sram_128x32/sram_128x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_128x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
